CREATE TABLE "AEROFOILS"
(
  "ID"                   NUMBER        NOT NULL ENABLE,
  "AEROFOIL_NAME"        VARCHAR2(256) NOT NULL ENABLE,
  "AEROFOIL_DESCRIPTION" VARCHAR2(256),
  CONSTRAINT "AEROFOILS_PK" PRIMARY KEY ("ID") ENABLE,
  CONSTRAINT "AEROFOILS_UK1" UNIQUE ("AEROFOIL_NAME") ENABLE
);

CREATE OR REPLACE TRIGGER "BI_AEROFOILS"
BEFORE INSERT ON "AEROFOILS"
FOR EACH ROW
  BEGIN
    IF :NEW."ID" IS NULL
    THEN
      SELECT "AEROFOILS_SEQ".nextval
      INTO :NEW."ID"
      FROM dual;
    END IF;
  END;

/
ALTER TRIGGER "BI_AEROFOILS" ENABLE;

